# workflows:
#   ios-app:
#     name: iOS App
#     environment:
#       vars: 
#         XCODE_PROJECT: "Runner"
#         XCODE_SCHEME: "Runner"
#       flutter: stable
#       xcode: latest
#       cocoapods: default
#     cache:
#       cache_paths:
#         - ~/.pub-cache
#     triggering:
#       events:
#         - push
#         - tag
#       branch_patterns:
#         - pattern: master
#           include: true
#           source: true
#     scripts:
#       # - xcodebuild build -workspace "$XCODE_WORKSPACE.xworkspace" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
#       - xcodebuild build -project "$XCODE_PROJECT.xcodeproj" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
#     artifacts:
#       - build/**/outputs/**/*.aab
#       - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
#       - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
#     publishing:
#       email:
#         recipients:
#           - matej.kratochvil33@seznam.cz
#       scripts:
#         - echo 'Post-publish script'
workflows:
  default-workflow: &baseline
    name: Default Workflow
    environment:
      flutter: stable
    cache:
      cache_paths:
        - $FCI_BUILD_DIR/build
    scripts:
      - |
        # set up debug keystore
        rm -f ~/.android/debug.keystore
        keytool -genkeypair \
          -alias androiddebugkey \
          -keypass android \
          -keystore ~/.android/debug.keystore \
          -storepass android \
          -dname 'CN=Android Debug,O=Android,C=US' \
          -keyalg 'RSA' \
          -keysize 2048 \
          -validity 10000        
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" \
          > "$FCI_BUILD_DIR/android/local.properties"        
      - flutter packages pub get
      - flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - matej.kratochvil33@seznam.cz
  stable-workflow:
      environment:
        flutter: beta