# workflows:
#   ios-app:
#     name: iOS App
#     environment:
#       vars: 
#         XCODE_PROJECT: "Runner"
#         XCODE_SCHEME: "Runner"
#       flutter: stable
#       xcode: latest
#       cocoapods: default
#     cache:
#       cache_paths:
#         - ~/.pub-cache
#     triggering:
#       events:
#         - push
#         - tag
#       branch_patterns:
#         - pattern: master
#           include: true
#           source: true
#     scripts:
#       # - xcodebuild build -workspace "$XCODE_WORKSPACE.xworkspace" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
#       - xcodebuild build -project "$XCODE_PROJECT.xcodeproj" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
#     artifacts:
#       - build/**/outputs/**/*.aab
#       - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
#       - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
#     publishing:
#       email:
#         recipients:
#           - matej.kratochvil33@seznam.cz
#       scripts:
#         - echo 'Post-publish script'
#workflows:
  # ANDROID INSTALACE FUNGUJE 
  # default-workflow: &baseline
  #   name: Default Workflow
  #   environment:
  #     flutter: stable
  #   cache:
  #     cache_paths:
  #       - $FCI_BUILD_DIR/build
  #   scripts:
  #     - |
  #       # set up debug keystore
  #       rm -f ~/.android/debug.keystore
  #       keytool -genkeypair \
  #         -alias androiddebugkey \
  #         -keypass android \
  #         -keystore ~/.android/debug.keystore \
  #         -storepass android \
  #         -dname 'CN=Android Debug,O=Android,C=US' \
  #         -keyalg 'RSA' \
  #         -keysize 2048 \
  #         -validity 10000        
  #     - |
  #       # set up local properties
  #       echo "flutter.sdk=$HOME/programs/flutter" \
  #         > "$FCI_BUILD_DIR/android/local.properties"        
  #     - flutter packages pub get
  #     - flutter build apk --release
  #   artifacts:
  #     - build/**/outputs/**/*.apk
  #     - build/**/outputs/**/*.aab
  #     - build/**/outputs/**/.ipa
  #     - build/**/outputs/**/mapping.txt
  #     - flutter_drive.log
  #   publishing:
  #     email:
  #       recipients:
  #         - matej.kratochvil33@seznam.cz
  # stable-workflow:
  #     environment:
  #       flutter: beta
workflows:
    ios-swiftly:
      name: TimeToPlan
      environment:
        vars:
          XCODE_WORKSPACE: "Runner.xcworkspace" # <-- Put the name of your workspace here. 
          XCODE_SCHEME: "Runner" # <-- Put the name of your scheme here.
        xcode: latest
        cocoapods: default
      triggering:
        events:
          - push
          - tag
          - pull_request
        branch_patterns:
          - pattern: 'master'
            include: true
            source: true
      scripts:
        - name: set up provisioning profiles
          script: |
            PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
            mkdir -p "$PROFILES_HOME"
            PROFILE_PATH="$(mktemp "$PROFILES_HOME"/$(uuidgen).mobileprovision)"
            echo ${CM_PROVISIONING_PROFILE} | base64 --decode > $PROFILE_PATH
            echo "Saved provisioning profile $PROFILE_PATH"
        - name: Add signing certificate to keychain
          script: |
            echo $CM_CERTIFICATE | base64 --decode > /tmp/certificate.p12
            keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password $CM_CERTIFICATE_PASSWORD
        - name: Increment build number
          script: |
            # increment build number
            #!/bin/sh
            set -e
            set -x
            cd $FCI_BUILD_DIR
            agvtool new-version -all $(($BUILD_NUMBER +1))
        - name: Set up code signing settings on Xcode project
          script: |
            xcode-project use-profiles
        - name: Build .ipa
          script: |
            xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
      artifacts:
        - build/ios/ipa/*.ipa
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      publishing:
        email:
            recipients:
              - matej.kratochvil33@seznam.cz
            notify:
              success: true
              failure: true
    
      

  