workflows:
  ios-app:
    name: iOS App
    enviroment:
      vars: 
        XCODE_PROJECT: "todoList"
        XCODE_SCHEME: "todoList"
      xcode: latest
      cocoapods: default
    scripts:
      - xcodebuild build -project "$XCODE_PROJECT.xcodeproj" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM