workflows:
  ios-app:
    name: iOS App
    environment:
      vars: 
        XCODE_PROJECT: "todoList"
        XCODE_SCHEME: "todoList"
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - xcodebuild build -project "$XCODE_PROJECT.xcodeproj" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/**/outputs/**/*.aab
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - matej.kratochvil33@seznam.cz
      scripts:
        - echo 'Post-publish script'